FORMAT: 1A

# gotdata

GOTData is a simple API allowing consumers to view data on the Novel series A Song of Ice and Fire.

## Character Collection [/characters]

### List All Characters [GET]

+ Response 200 (application/json)

        {
            "character_list": "A list of Characters in A Song of Ice and Fire.",
            "characters": [
                {
                    "url": "https://anapioficeandfire.com/api/characters/583",
                    "name": "Jon Snow",
                    "gender": "Male",
                    "culture": "Northmen",
                    "born": "In 283 AC",
                    "died": "",
                    "titles": [
                        "Lord Commander of the Night's Watch"
                    ],
                    "aliases": [
                        "Lord Snow",
                        "Ned Stark's Bastard",
                        "The Snow of Winterfell",
                        "The Crow-Come-Over",
                        "The 998th Lord Commander of the Night's Watch",
                        "The Bastard of Winterfell",
                        "The Black Bastard of the Wall",
                        "Lord Crow"
                    ],
                    "father": "",
                    "mother": "",
                    "spouse": "",
                    "allegiances": [
                        "https://anapioficeandfire.com/api/houses/362"
                    ],
                    "books": [
                        "https://anapioficeandfire.com/api/books/5"
                    ],
                    "povBooks": [
                        "https://anapioficeandfire.com/api/books/1",
                        "https://anapioficeandfire.com/api/books/2",
                        "https://anapioficeandfire.com/api/books/3",
                        "https://anapioficeandfire.com/api/books/8"
                    ],
                    "tvSeries": [
                        "Season 1",
                        "Season 2",
                        "Season 3",
                        "Season 4",
                        "Season 5"
                    ],
                    "playedBy": [
                        "Kit Harington"
                    ],
                }, {
                    "url": "https://anapioficeandfire.com/api/characters/1303",
                    "name": "Daenerys Targaryen",
                    "gender": "Female",
                    "culture": "Valyrian",
                    "born": "In 284 AC, at Dragonstone",
                    "died": "",
                    "titles": [
                        "Queen of the Andals and the Rhoynar and the First Men, Lord of the Seven Kingdoms",
                        "Khaleesi of the Great Grass Sea",
                        "Breaker of Shackles/Chains",
                        "Queen of Meereen",
                        "Princess of Dragonstone"
                    ],
                    "aliases": [
                        "Dany",
                        "Daenerys Stormborn",
                        "The Unburnt",
                        "Mother of Dragons",
                        "Mother",
                        "Mhysa",
                        "The Silver Queen",
                        "Silver Lady",
                        "Dragonmother",
                        "The Dragon Queen",
                        "The Mad King's daughter"
                    ],
                    "father": "",
                    "mother": "",
                    "spouse": "https://anapioficeandfire.com/api/characters/1346",
                    "allegiances": [
                        "https://anapioficeandfire.com/api/houses/378"
                    ],
                    "books": [
                        "https://anapioficeandfire.com/api/books/5"
                    ],
                    "povBooks": [
                        "https://anapioficeandfire.com/api/books/1",
                        "https://anapioficeandfire.com/api/books/2",
                        "https://anapioficeandfire.com/api/books/3",
                        "https://anapioficeandfire.com/api/books/8"
                    ],
                    "tvSeries": [
                        "Season 1",
                        "Season 2",
                        "Season 3",
                        "Season 4",
                        "Season 5"
                    ],
                    "playedBy": [
                        "Emilia Clarke"
                    ],
                }, {
                    "url": "https://anapioficeandfire.com/api/characters/1346",
                    "name": "Drogo",
                    "gender": "Male",
                    "culture": "Dothraki",
                    "born": "In or around 267 AC",
                    "died": "In 298 AC, at Dothraki sea",
                    "titles": [
                        "Khal"
                    ],
                    "aliases": [
                        "Great Rider",
                        "Great Khal"
                    ],
                    "father": "",
                    "mother": "",
                    "spouse": "https://anapioficeandfire.com/api/characters/1303",
                    "allegiances": [],
                    "books": [
                        "https://anapioficeandfire.com/api/books/1",
                        "https://anapioficeandfire.com/api/books/2",
                        "https://anapioficeandfire.com/api/books/3",
                        "https://anapioficeandfire.com/api/books/8"
                    ],
                    "povBooks": [],
                    "tvSeries": [
                        "Season 1",
                        "Season 2"
                    ],
                    "playedBy": [
                        "Jason Momoa"
                    ],
                },
            ],
        }

## House Collection [/houses]

### List All Houses [GET]

+ Response 200 (application/json)

        {
            "house_list": "A list of Houses in A Song of Ice and Fire.",
            "houses": [
                {
                    "url": "https://anapioficeandfire.com/api/houses/378",
                    "name": "House Targaryen of King's Landing",
                    "region": "The Crownlands",
                    "coatOfArms": "Sable, a dragon thrice-headed gules",
                    "words": "Fire and Blood",
                    "titles": [
                        "King of the Andals, the Rhoynar and the First Men",
                        "Lord of the Seven Kingdoms",
                        "Prince of Summerhall"
                    ],
                    "seats": [
                        "Red Keep (formerly)",
                        "Summerhall (formerly)"
                    ],
                    "currentLord": "https://anapioficeandfire.com/api/characters/1303",
                    "heir": "",
                    "overlord": "",
                    "founded": "House Targaryen: >114 BCHouse Targaryen of King's Landing:1 AC",
                    "founder": "",
                    "diedOut": "",
                    "ancestralWeapons": [
                        "Blackfyre",
                        "Dark Sister"
                    ],
                    "cadetBranches": [
                        "https://anapioficeandfire.com/api/houses/23"
                    ],
                    "swornMembers": [
                        "https://anapioficeandfire.com/api/characters/33",
                        "https://anapioficeandfire.com/api/characters/42",
                        "https://anapioficeandfire.com/api/characters/43",
                        "https://anapioficeandfire.com/api/characters/44",
                        "https://anapioficeandfire.com/api/characters/45",
                        "https://anapioficeandfire.com/api/characters/48",
                        "https://anapioficeandfire.com/api/characters/49",
                        "https://anapioficeandfire.com/api/characters/55",
                        "https://anapioficeandfire.com/api/characters/58",
                        "https://anapioficeandfire.com/api/characters/59",
                        "https://anapioficeandfire.com/api/characters/76",
                        "https://anapioficeandfire.com/api/characters/91",
                        "https://anapioficeandfire.com/api/characters/93",
                        "https://anapioficeandfire.com/api/characters/109",
                        "https://anapioficeandfire.com/api/characters/110"
                    ],
                }, {
                    "url": "https://anapioficeandfire.com/api/houses/229",
                    "name": "House Lannister of Casterly Rock",
                    "region": "The Westerlands",
                    "coatOfArms": "A gold lion, on a crimson field(Gules, a lion or)",
                    "words": "Hear Me Roar!",
                    "titles": [
                        "King of the Rock (formerly) Lord of Casterly Rock",
                        "Shield of Lannisport",
                        "Warden of the West"
                    ],
                    "seats": [
                        "Casterly Rock"
                    ],
                    "currentLord": "https://anapioficeandfire.com/api/characters/238",
                    "heir": "",
                    "overlord": "https://anapioficeandfire.com/api/houses/16",
                    "founded": "Age of Heroes",
                    "founder": "https://anapioficeandfire.com/api/characters/615",
                    "diedOut": "",
                    "ancestralWeapons": [
                        "Brightroar"
                    ],
                    "cadetBranches": [
                        "https://anapioficeandfire.com/api/houses/228",
                        "https://anapioficeandfire.com/api/houses/230",
                        "https://anapioficeandfire.com/api/houses/231",
                        "https://anapioficeandfire.com/api/houses/232",
                        "https://anapioficeandfire.com/api/houses/233"
                    ],
                    "swornMembers": [
                        "https://anapioficeandfire.com/api/characters/27",
                        "https://anapioficeandfire.com/api/characters/101",
                        "https://anapioficeandfire.com/api/characters/115",
                        "https://anapioficeandfire.com/api/characters/177",
                        "https://anapioficeandfire.com/api/characters/235",
                        "https://anapioficeandfire.com/api/characters/236",
                        "https://anapioficeandfire.com/api/characters/238",
                        "https://anapioficeandfire.com/api/characters/282",
                        "https://anapioficeandfire.com/api/characters/283",
                        "https://anapioficeandfire.com/api/characters/284",
                        "https://anapioficeandfire.com/api/characters/292",
                        "https://anapioficeandfire.com/api/characters/294",
                        "https://anapioficeandfire.com/api/characters/363",
                        "https://anapioficeandfire.com/api/characters/367",
                        "https://anapioficeandfire.com/api/characters/377",
                        "https://anapioficeandfire.com/api/characters/382",
                        "https://anapioficeandfire.com/api/characters/415",
                        "https://anapioficeandfire.com/api/characters/418",
                        "https://anapioficeandfire.com/api/characters/422",
                        "https://anapioficeandfire.com/api/characters/529"
                    ],
                }, {
                    "url": "https://anapioficeandfire.com/api/houses/362",
                    "name": "House Stark of Winterfell",
                    "region": "The North",
                    "coatOfArms": "A running grey direwolf, on an ice-white field",
                    "words": "Winter is Coming",
                    "titles": [
                        "King in the North",
                        "Lord of Winterfell",
                        "Warden of the North",
                        "King of the Trident"
                    ],
                    "seats": [
                        "Scattered (formerly Winterfell)"
                    ],
                    "currentLord": "",
                    "heir": "",
                    "overlord": "https://anapioficeandfire.com/api/houses/16",
                    "founded": "Age of Heroes",
                    "founder": "https://anapioficeandfire.com/api/characters/209",
                    "diedOut": "",
                    "ancestralWeapons": [
                        "Ice"
                    ],
                    "cadetBranches": [
                        "https://anapioficeandfire.com/api/houses/170",
                        "https://anapioficeandfire.com/api/houses/215"
                    ],
                    "swornMembers": [
                        "https://anapioficeandfire.com/api/characters/2",
                        "https://anapioficeandfire.com/api/characters/20",
                        "https://anapioficeandfire.com/api/characters/97",
                        "https://anapioficeandfire.com/api/characters/98",
                        "https://anapioficeandfire.com/api/characters/136",
                        "https://anapioficeandfire.com/api/characters/143",
                        "https://anapioficeandfire.com/api/characters/148",
                        "https://anapioficeandfire.com/api/characters/170",
                        "https://anapioficeandfire.com/api/characters/181",
                        "https://anapioficeandfire.com/api/characters/192",
                        "https://anapioficeandfire.com/api/characters/206",
                        "https://anapioficeandfire.com/api/characters/207",
                        "https://anapioficeandfire.com/api/characters/208",
                        "https://anapioficeandfire.com/api/characters/209",
                        "https://anapioficeandfire.com/api/characters/210",
                        "https://anapioficeandfire.com/api/characters/212",
                        "https://anapioficeandfire.com/api/characters/216",
                        "https://anapioficeandfire.com/api/characters/232"
                    ],
                },
            ],
        }
        
## Events Collection [/events]

### List All Events [GET]

+ Response 200 (application/json)

        {
            "event_list": "A list of Events in A Song of Ice and Fire.",
            "events": [
                {
                    "name": "Red Wedding",
                    "date": "299 AC",
                    "location": [
                        "The Twins",
                        "Riverlands"
                    ],
                    "result": [
                        "Iron Throne Victory",
                        "Robb Stark and most of his loyal soldiers killed ",
                        "Roose Bolton declared as the new Warden of the North",
                    ],
                    "combatant1": "House Stark",
                    "combatant2": [
                        "House Frey",
                        "House Bolton"
                    ],
                    "commander1": "King Robb Stark",
                    "commander2": [
                        "Lord Walder Frey",
                        "Lord Roose Bolton",
                        "Ser Walder Rivers",
                    ],
                }, {
                    "battle_name": "Battle of the Bells",
                    "conflict": "Robert's Rebellion",
                    "date": "Date|283}}",
                    "place": "Stoney Sept",
                    "result": "Rebel victory",
                    "combatant1":  [
                        "Rebel army of North Riverlands Vale Stormlands",
                    ],
                    "combatant2": "Royal army of King's Landing ",
                    "commander1": [
                        "Lord Eddard Stark",
                        "Lord Hoster TullyLord",
                        "Robert Baratheon",
                    ],
                    "commander2": "Lord Jon Connington",
                    "casualties1": "Ser Denys Arryn",
                }, {
                    "name": "Battle at Fairmarket",
                    "place": "Fairmarket",
                    "result": "House Hoare victory",
                    "combatant1": [
                        "House Hoare",
                        "House Bracken",
                        "House Charlton",
                        "House Goodbrook",
                        "House Paege",
                        "House Vypren",
                    ],
                    "combatant2": "House Durrandon",
                    "commander1": [
                        "Harwyn Hoare",
                        "Lothar Bracken",
                        "Theo Charlton",
                    ],
                    "commander2": "Arrec Durrandon",
                    "casualties1": "unknown",
                    "casualties2": [
                        "Half lost",
                        "Two brothers of Arrect",
                    ],
                },
            ],
        }
        
## Location Collection [/locations]

### List All Locations [GET]

+ Response 200 (application/json)

        {
            "location_list": "A list of Locations in A Song of Ice and Fire.",
            "locations": [
                {
                
                }, {
                   
                }, {
                
                },
            ],
        }